
services:
  python-app:
    build: ./python
    #stdin_open: true
    #tty: true
    ports:
      - "5001:5000"
  php-app:
      build: ./php
       #context: ./php
       #dockerfile: Dockerfile # ここでDockerfileを指定
      ports:
        - "8080:80"
      volumes:
        - ./php:/var/www/html/
      depends_on:
       python-app:
        condition: service_started
#       version: "3.8"
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile-php
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: userpassword
#   db:
#     image: mysql:5.7
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: userpassword
#     volumes:
#       - mysql-data:/var/lib/mysql
#   python-app:
#     build:
#       context: ./python
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"  # 例: Flaskアプリが5000ポートで動作する場合
#     volumes:
#       - ./python:/app
#     depends_on:
#       - db

# volumes:
#   mysql-data: